export const authConstants = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_FAILURE : "LOGIN_FAILURE",
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGOUT_REQUEST : "LOGOUT_REQUEST",
};

export const userConstants = {
    USER_REGISTER_REQUEST : "USER_REGISTER_REQUEST",
    USER_REGISTER_FAILURE : "USER_REGISTER_LOGIN_FAILURE",
    USER_REGISTER_SUCCESS : "USER_REGISTER_SUCCESS",
}

export const blogConstants = {
    ALL_BLOGS_REQUEST : "ALL_BLOGS_REQUEST",
    ALL_BLOGS_SUCCESS : "ALL_BLOGS_SUCCESS",
    ALL_BLOGS_FAILURE : "ALL_BLOGS_FAILURE",
}